### PR TITLE
#154953748 Enable social media logins

### PR DESCRIPTION
**Pull request by pndemo**
#### What does this PR do?
* Allows users to use their social media accounts to login to the Wger application

#### Description of Task to be completed?
* Enable users to login via Facebook
* Enable users to login via Google
* Enable users to login via Twitter

#### How should this be manually tested?
After cloning the Repo, cd into it and activate the virtual environment. Install requirements into the virtual environment and run the following commands:

$./manage.py migrate
$./manage.py test

#### What are the relevant pivotal tracker stories?
#154953748

### CODE REVIEW

**Comment by pndemo** [comment]
@collin5 This error is due to missing client ids and client secrets in the settings/.env file you are using. I didn't add them to the settings file due to security concerns. I have added them though to the Travis CI env variables and will be adding to the heroku env variables too.

**Comment by collin5** [comment]
Alright, let me have a look. But can you please rebase your PR with develop so I can easily review changes.

**Comment by pndemo** [comment]
@collin5 Thanks.. Let me do that.

**Comment by collin5** [comment]
And could you also change this "-- Or use Social Login --" to just "-- Or -- "

**Comment by pndemo** [comment]
@collin5 Sure, let me make the changes

**Comment by collin5** [comment]
Also check your slack, just sent you a DM

**Pull request merged**
