### PR TITLE
Ft exercise info 154953731

### PR DESCRIPTION
**Pull request by philophilo**
#### What does this PR do?
* Creates a serializer for the read-only API
* Creates a read-only API for all information about exercises 
#### How should this be manually tested?
* Visit the wger application here. ["Landing page"](https://wg-kalii.herokuapp.com/)
#### What are the relevant pivotal tracker stories?
*  [154953731](https://www.pivotaltracker.com/story/show/154953731)

### CODE REVIEW

**Comment by philophilo** [comment]
This task has been completed @collin5, please review.

**Comment by philophilo** [comment]
wow, I had not seen that. am on it @collin5

**Comment by philophilo** [comment]
I have been able to finish the endpoint that allows ids for a particular exercise `/api/v2/exercisedetails/<id>/`

**Comment by philophilo** [comment]
Alright adding that too, had not seen this though.

**Comment by philophilo** [comment]
@collin5 the tests have been corrected

**Comment by collin5** [comment]
Hi @philophilo I see you are just adding tests to check for muscle objects. By detail, I mean instead of muscles being `muscles: [1,2,3,...]` (with just ids), They should be objects e.g
 ```
muscles: [ 
    {
      ... all muscle details
    },
    {
      ... another all muscle details
    }
]
```
Same for `"muscles_secondary": []` and `"equipment": []`
We can have a sync if you want clarification on this.

**Comment by philophilo** [comment]
@collin5, I hope this satisfies the story

**Comment by collin5** [comment]
This looks perfect now. Thank you 👍

**Pull request merged**
